# Generated by Django 2.2.17 on 2021-04-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Telemedicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('home_address', models.TextField()),
                ('oxygen_saturation', models.CharField(blank=True, max_length=200)),
                ('pulse', models.IntegerField(blank=True)),
                ('contact', models.CharField(max_length=20)),
                ('person_accompany_name', models.CharField(blank=True, max_length=200)),
                ('person_accompany_phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
