# Generated by Django 2.2.17 on 2021-04-26 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specilization', models.CharField(max_length=200)),
                ('years_of_practice', models.IntegerField()),
                ('hospital_name', models.CharField(max_length=300)),
                ('consulting_hour', models.CharField(max_length=300)),
            ],
        ),
    ]
