# Generated by Django 2.2.17 on 2021-04-26 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rescue', '0003_auto_20210426_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='telemedicine',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='telemedicine',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telemedicine',
            name='oxygen_saturation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telemedicine',
            name='patient_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='telemedicine',
            name='person_accompany_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='telemedicine',
            name='person_accompany_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='telemedicine',
            name='pulse',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
