# Generated by Django 2.2.17 on 2021-04-27 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0004_auto_20210426_1250'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hashtag', models.CharField(max_length=300)),
                ('link', models.TextField(null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
