# Generated by Django 2.2.17 on 2021-04-27 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0005_city_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='color',
            field=models.CharField(choices=[('blue', 'blue'), ('yellow', 'yellow'), ('red', 'red'), ('green', 'green'), ('indigo', 'indigo'), ('purple', 'purple'), ('pink', 'pink')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resource',
            name='hashtag',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
