# Generated by Django 2.2.17 on 2021-05-05 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0009_auto_20210505_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messageboard',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='messageboard',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
