# Generated by Django 2.2.17 on 2021-05-06 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0012_auto_20210506_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemedicine',
            name='pulse',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
