# Generated by Django 2.2.17 on 2021-05-06 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0013_auto_20210506_1302'),
    ]

    operations = [
        migrations.RenameField(
            model_name='telemedicine',
            old_name='home_address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='telemedicine',
            old_name='patient_name',
            new_name='name',
        ),
    ]
